Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/python310/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/python310/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/python310/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/python310/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/python310/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/python310/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/python310/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/python310/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
tabelle.loc['Dacia Nr. 1'] = ['dacia', 'Dacia Duster', 'orange', '03/2023', 2023, 25749, 84, 114, 'Schaltgetriebe', 'Diesel', 5.3, 140, 5.0, 'Journey Blue dCi 115 4x4'] 
tabelle.head(11)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[13], line 1[0m
[0;32m----> 1[0m tabelle[38;5;241m.[39mloc[[38;5;124m'[39m[38;5;124mDacia Nr. 1[39m[38;5;124m'[39m] [38;5;241m=[39m [[38;5;124m'[39m[38;5;124mdacia[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mDacia Duster[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124morange[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124m03/2023[39m[38;5;124m'[39m, [38;5;241m2023[39m, [38;5;241m25749[39m, [38;5;241m84[39m, [38;5;241m114[39m, [38;5;124m'[39m[38;5;124mSchaltgetriebe[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mDiesel[39m[38;5;124m'[39m, [38;5;241m5.3[39m, [38;5;241m140[39m, [38;5;241m5.0[39m, [38;5;124m'[39m[38;5;124mJourney Blue dCi 115 4x4[39m[38;5;124m'[39m] 
[1;32m      2[0m tabelle[38;5;241m.[39mhead([38;5;241m11[39m)

File [0;32m/opt/homebrew/Caskroom/miniconda/base/envs/python310/lib/python3.10/site-packages/pandas/core/indexing.py:818[0m, in [0;36m_LocationIndexer.__setitem__[0;34m(self, key, value)[0m
[1;32m    815[0m [38;5;28mself[39m[38;5;241m.[39m_has_valid_setitem_indexer(key)
[1;32m    817[0m iloc [38;5;241m=[39m [38;5;28mself[39m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mname [38;5;241m==[39m [38;5;124m"[39m[38;5;124miloc[39m[38;5;124m"[39m [38;5;28;01melse[39;00m [38;5;28mself[39m[38;5;241m.[39mobj[38;5;241m.[39miloc
[0;32m--> 818[0m [43miloc[49m[38;5;241;43m.[39;49m[43m_setitem_with_indexer[49m[43m([49m[43mindexer[49m[43m,[49m[43m [49m[43mvalue[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mname[49m[43m)[49m

File [0;32m/opt/homebrew/Caskroom/miniconda/base/envs/python310/lib/python3.10/site-packages/pandas/core/indexing.py:1785[0m, in [0;36m_iLocIndexer._setitem_with_indexer[0;34m(self, indexer, value, name)[0m
[1;32m   1782[0m     indexer, missing [38;5;241m=[39m convert_missing_indexer(indexer)
[1;32m   1784[0m     [38;5;28;01mif[39;00m missing:
[0;32m-> 1785[0m         [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_setitem_with_indexer_missing[49m[43m([49m[43mindexer[49m[43m,[49m[43m [49m[43mvalue[49m[43m)[49m
[1;32m   1786[0m         [38;5;28;01mreturn[39;00m
[1;32m   1788[0m [38;5;28;01mif[39;00m name [38;5;241m==[39m [38;5;124m"[39m[38;5;124mloc[39m[38;5;124m"[39m:
[1;32m   1789[0m     [38;5;66;03m# must come after setting of missing[39;00m

File [0;32m/opt/homebrew/Caskroom/miniconda/base/envs/python310/lib/python3.10/site-packages/pandas/core/indexing.py:2160[0m, in [0;36m_iLocIndexer._setitem_with_indexer_missing[0;34m(self, indexer, value)[0m
[1;32m   2157[0m     [38;5;28;01mif[39;00m is_list_like_indexer(value):
[1;32m   2158[0m         [38;5;66;03m# must have conforming columns[39;00m
[1;32m   2159[0m         [38;5;28;01mif[39;00m [38;5;28mlen[39m(value) [38;5;241m!=[39m [38;5;28mlen[39m([38;5;28mself[39m[38;5;241m.[39mobj[38;5;241m.[39mcolumns):
[0;32m-> 2160[0m             [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mcannot set a row with mismatched columns[39m[38;5;124m"[39m)
[1;32m   2162[0m     value [38;5;241m=[39m Series(value, index[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39mobj[38;5;241m.[39mcolumns, name[38;5;241m=[39mindexer)
[1;32m   2164[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mlen[39m([38;5;28mself[39m[38;5;241m.[39mobj):
[1;32m   2165[0m     [38;5;66;03m# We will ignore the existing dtypes instead of using[39;00m
[1;32m   2166[0m     [38;5;66;03m#  internals.concat logic[39;00m

[0;31mValueError[0m: cannot set a row with mismatched columns
ValueError: cannot set a row with mismatched columns

