Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/python312/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/python312/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/python312/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/python312/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/python312/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/python312/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/python312/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import plotly.express as px

import pandas as pd 

daten = pd.DataFrame({
    'Feature 1': X[:,0],
    'Feature 2': X[:,1],
    'Status': bool(y),
    })

fig = px.scatter(daten, x = 'Feature 1', y = 'Feature 2',  color='Status',
                 title='KÃ¼nstliche Daten')
fig.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[2], line 8[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mplotly[39;00m[38;5;21;01m.[39;00m[38;5;21;01mexpress[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpx[39;00m
[1;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m 
[1;32m      5[0m daten [38;5;241m=[39m pd[38;5;241m.[39mDataFrame({
[1;32m      6[0m     [38;5;124m'[39m[38;5;124mFeature 1[39m[38;5;124m'[39m: X[:,[38;5;241m0[39m],
[1;32m      7[0m     [38;5;124m'[39m[38;5;124mFeature 2[39m[38;5;124m'[39m: X[:,[38;5;241m1[39m],
[0;32m----> 8[0m     [38;5;124m'[39m[38;5;124mStatus[39m[38;5;124m'[39m: [38;5;28;43mbool[39;49m[43m([49m[43my[49m[43m)[49m,
[1;32m      9[0m     })
[1;32m     11[0m fig [38;5;241m=[39m px[38;5;241m.[39mscatter(daten, x [38;5;241m=[39m [38;5;124m'[39m[38;5;124mFeature 1[39m[38;5;124m'[39m, y [38;5;241m=[39m [38;5;124m'[39m[38;5;124mFeature 2[39m[38;5;124m'[39m,  color[38;5;241m=[39m[38;5;124m'[39m[38;5;124mStatus[39m[38;5;124m'[39m,
[1;32m     12[0m                  title[38;5;241m=[39m[38;5;124m'[39m[38;5;124mKÃ¼nstliche Daten[39m[38;5;124m'[39m)
[1;32m     13[0m fig[38;5;241m.[39mshow()

[0;31mValueError[0m: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

